---
image: circleci/ruby:3.0.3-node-browsers

variables:
  CACHE_FALLBACK_KEY: "$CI_COMMIT_REF_SLUG"

before_script:
  - bundle config set path 'vendor'  # Install dependencies into ./vendor/ruby

stages:
  - test

test:
  stage: test
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
    - key:
        files:
          - yarn.lock
      paths:
        - ".yarn-cache/"
  script:
    - bundle install -j $(nproc)
    - yarn install --cache-folder .yarn-cache
    - bin/rails db:drop RAILS_ENV=test
    - bin/rails db:setup RAILS_ENV=test
    - bundle exec standardrb
    - bin/rails test
    - bin/rails test:system
